// export const CREATE_CARD = "CREATE_CARD";
// export const DELETE_CARD = "DELETE_CARD";
// export const EDIT_CARD = "EDIT_CARD";

export const GET_CARDS_REQUEST = "GET_CARDS_REQUEST";
export const GET_CARDS_SUCCESS = "GET_CARDS_SUCCESS";
export const GET_CARDS_FAILURE = "GET_CARDS_FAILURE";
export const CREATE_CARD_REQUEST = "CREATE_CARD_REQUEST";
export const CREATE_CARD_SUCCESS = "CREATE_CARD_SUCCESS";
export const CREATE_CARD_FAILURE = "CREATE_CARD_FAILURE";
export const DELETE_CARD_REQUEST = "DELETE_CARD_REQUEST";
export const DELETE_CARD_SUCCESS = "DELETE_CARD_SUCCESS";
export const DELETE_CARD_FAILURE = "DELETE_CARD_FAILURE";
export const EDIT_CARD_REQUEST = "EDIT_CARD_REQUEST";
export const EDIT_CARD_SUCCESS = "EDIT_CARD_SUCCESS";
export const EDIT_CARD_FAILURE = "EDIT_CARD_FAILURE";
